name: Deploy

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  deploy:

    if: github.repository == 'quarkusio/quarkus-github-lottery'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Set up JDK 25
      uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
      with:
        distribution: temurin
        java-version: 25

    - name: Install CLI tools from OpenShift Mirror
      uses: redhat-actions/openshift-tools-installer@144527c7d98999f2652264c048c7a9bd103f8a82 # v1.13.1
      with:
        oc: "latest"

    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@f19c5f4f98c725396a5eeb265b1338333634828a # v2.0
      with:
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
        openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}

    - name: Delete problematic image
      run: oc delete is ubi-quarkus-native-binary-s2i || true

    - name: Build and deploy
      run: mvn -B clean package -Dquarkus.kubernetes.deploy=true -Dquarkus.native.container-build=true -Dnative -Drevision=${{ github.sha }}
